---
title: "Progress Memo 1"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Ada"
date: today

format:
  html:
    toc: true
    embed-resources: true
    
execute:
  echo: false
  warning: false

from: markdown+emoji 
---

::: {.callout-tip icon=false}

## Github Repo Link

[https://github.com/stat301-1-2023-fall/final-project-1-adacliu.git](https://github.com/stat301-1-2023-fall/final-project-1-adacliu.git)

:::

::: {.callout-warning}
GitHub (free account) cannot store large files. If you try to commit and push a large dataset you will have an ERROR! Any file over 100 MB (100,000 KB) needs to be added to the `.gitignore` file BEFORE committing.

**We may need to do that for files in your final project!**
:::

## Data source

I plan to do my EDA project using the Global Terrorism Database (GTD) from Kaggle. This database is an open source database that has information on terrorist attacks worldwide from 1970 to 2017 and is maintained by the National Consortium for the Study of Terrorism and Responses to Terrorism at The University of Maryland. The database can be found at https://www.kaggle.com/datasets/START-UMD/gtd/ .

## Why this data

Blah blah blah^[another footnote]

## Data quality & complexity check

Blah blah blah

## Potential data issues

Blah blah blah

## Misc

Blah Blah
